import Footer from "../components/footer";
import NavBar from "../components/nav-bar";
import "../styles/globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["devanagari"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${poppins.className}`}>
        <section>
          <NavBar></NavBar>
        </section>
        {children}
        <section>
          <Footer></Footer>
        </section>
      </body>
    </html>
  );
}
