import fs from "fs/promises";
import Head from "next/head";
import path from "path";
import AboutMe from "../components/about-me";
import Contact from "../components/contact";
import Hero from "../components/hero";
import Portoflio from "../components/portfolio/portfolio";
import getFileStructure from "../components/ffmpeg";
import Services from "../components/services";
import EventList from "../components/events/event-list";

export default async function HomePage() {
  const portfolioJsonPath = path.join(process.cwd(), "data", "portfolio.json");
  const servicesJsonpath = path.join(process.cwd(), "data", "services.json");

  const dataJson = await fs
    .readFile(portfolioJsonPath, "utf-8")
    .then((res) => JSON.parse(res));

  const servicesJson = await fs
    .readFile(servicesJsonpath, "utf-8")
    .then((res) => JSON.parse(res));

  const portfolioResult: any[] = [];

  for (const portfolioItem of dataJson.portfolio) {
    const relativePath = "/images/portfolio/" + portfolioItem.imagesPath;
    const resolvedImages = await getFileStructure(
      process.cwd() + "/public" + relativePath,
      relativePath
    );
    portfolioResult.push({
      imagesPath: portfolioItem.imagesPath,
      title: portfolioItem.title,
      images: resolvedImages.map((image) => {
        return {
          ...image,
          displayViewButton: false,
          viewFullGallery: false,
        };
      }),
    });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Hero></Hero>
      </section>
      <section id="portfolio">
        <Portoflio portfolioResult={portfolioResult}></Portoflio>
      </section>
      <section id="about-me">
        <AboutMe></AboutMe>
      </section>
      <section id="services">
        <Services services={servicesJson.services}></Services>
      </section>
      <section>
        <EventList></EventList>
      </section>
      <section id="contact">
        <Contact></Contact>
      </section>
    </>
  );
}
