import path from "path";
import Head from "next/head";
import { Poppins } from "next/font/google";
import NavBar from "../../components/nav-bar";
import Hero from "../../components/hero";
import Portoflio from "../../components/portfolio/portfolio";
import Footer from "../../components/footer";
import AboutMe from "../../components/about-me";
import Contact from "../../components/contact";
import fs from "fs/promises";

import getFileStructure from "../../components/ffmpeg";

const poppins = Poppins({ subsets: ["devanagari"], weight: "400" });
export default async function HomePage() {
  const dataJsonPath = path.join(process.cwd(), "data", "data.json");

  const dataJson = await fs
    .readFile(dataJsonPath, "utf-8")
    .then((res) => JSON.parse(res));

  const portfolioResult: any[] = [];

  for (const portfolioItem of dataJson.portfolio) {
    const relativePath = "/images/portfolio/" + portfolioItem.imagesPath;
    const resolvedImages = await getFileStructure(
      process.cwd() + "/public" + relativePath,
      relativePath
    );
    portfolioResult.push({
      imagesPath: portfolioItem.imagesPath,
      title: portfolioItem.title,
      images: resolvedImages.map((image) => {
        return {
          ...image,
          displayViewButton: false,
          viewFullGallery: false,
        };
      }),
    });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={` ${poppins.className}`}>
        <section>
          <NavBar></NavBar>
        </section>
        <section>
          <Hero></Hero>
        </section>
        <section id="portfolio">
          <Portoflio portfolioResult={portfolioResult}></Portoflio>
        </section>
        <section id="about-me">
          <AboutMe></AboutMe>
        </section>
        <section id="contact">
          <Contact></Contact>
        </section>
        <section>
          <Footer></Footer>
        </section>
      </main>
    </>
  );
}
